---
title: "Annexe"
author: "Quentin Merrien et Catherine Berleur"
date: "13/04/2021"
output:
  pdf_document:
    toc: yes
    toc_depth : 3
    latex_engine: xelatex
  html_document:
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

knitr::opts_chunk$set(out.height = '300pt', fig.align = 'center')

## Packages ----
library(tidyverse)
library(ggforce)
library(sf)
library(haven)
library(FactoMineR)
library(ggrepel)
library('kableExtra')
library(knitr)
library(stargazer)
library(questionr)
#install.packages("remotes")
#remotes::install_github("easystats/easystats")
#install.packages("qqplotr")
library(qqplotr)
library("easystats")
#install.packages("ggraph")
library(ggraph)
library(dplyr)
library(see)
 # install.packages("ggcorrplot")                      # Install corrplot package
library(ggcorrplot)

## Données -----

setwd("C:/Users/quent/Desktop/ENS Paris-Saclay/1A/1S2/Econométrie/TDs/Bases de données/Documents/projet-econometrie")
# setwd("~/Documents/ENS/econometrie/projet_r")

base_complete <- read_csv("base_complete.csv") %>%
   mutate(code2 = as.character(code2))

```
\newpage

## Annexe 1 

```` {r, results = "asis" }

stargazer(as.data.frame(base_complete), title = "Principaux indicateurs des variables", header = F )

```

## Annexe 2
```{r}
graph1 <- ggplot(data = base_complete, 
                 mapping = aes(y= reorder(Nom_pays, depenses_brutes_env), 
                               x = depenses_brutes_env,
                               fill = depenses_brutes_env)) +
          geom_col()

graph1 <- graph1 + labs(title = "Les dépenses nationales pour la protection de l'environnement",
         y = "Pays", 
         x = "NEEP brutes",
         fill = NULL,
         subtitle= "des pays Européen en million d'euros")

print(graph1)

graph2 <- ggplot(data = base_complete, 
                 mapping = aes(y=reorder(Nom_pays, part_depenses_env), 
                               x = part_depenses_env,
                               fill = part_depenses_env)) +
  geom_col()

graph2 <- graph2 + labs(title = "Les dépenses nationales pour la protection de l'environnement ",
         y = "Pays", 
         x = "Part des dépenses environnementales dans le PIB",
         fill = NULL,
         subtitle= "des pays Européens en points de PIB")

print(graph2)


```

## Annexe 3
```` {r}

europe             <- st_read("Europe/europe.shp", quiet = T)

codes              <- read.csv("all.csv") %>%
  filter(region == "Europe")%>%
  select(name, alpha.2) %>%
  mutate (NAME = name,
          c_abrv = alpha.2)

carte_europe       <- europe %>%
  full_join(codes, by = "NAME")

carte_europe       <- carte_europe %>%
  full_join(base_complete, by = c("c_abrv"= "Pays"))
  # filter(sensi_env != "NA")

ggplot(data = carte_europe) +
  geom_sf(aes(fill = sensi_env)) +
  ggtitle("Figure VI - Sensibilité environnementale en Europe") +
  coord_sf(datum = NA) +
  scale_fill_gradientn(colours = c("white", "darkolivegreen1", "yellowgreen","forestgreen", "darkgreen"))

```

## Annexe 4


```{r}


 resultat_ACP     <- PCA(base_complete[, 5:14], graph= F)

dbact            <-as_tibble(resultat_ACP$var$coord) %>%
  mutate(names=c(rownames(resultat_ACP$var$coord)))

dbind            <-bind_cols(base_complete,as_tibble(resultat_ACP$ind$coord))

# resultat_classif <- HCPC(resultat_ACP, nb.clust = 4, graph = FALSE)

# dbind            <- dbind %>%
#   ungroup() %>%
#   mutate(groupe = resultat_classif$data.clust$clust)


barplot(resultat_ACP$eig[,2],main="Figure I - Part expliquée par chaque axe dans la variance totale",
      names.arg=1:nrow(resultat_ACP$eig),col= rainbow (15))

kable(resultat_ACP$eig, caption = "Tableau des valeurs propres et \nvariances des composantes principales")


ggplot(dbact,aes(x=Dim.1,y= Dim.2,label=names))+
  geom_point()+
  theme(legend.title=element_blank(),
        panel.background =element_rect(fill="white")) +
  geom_text_repel(size=4,show.legend = FALSE)+
  geom_hline(yintercept=0,linetype="dashed",colour="grey")+
  geom_vline(xintercept = 0,linetype="dashed",colour="grey")+
  ggtitle("Espace des variables de l'ACP avec les axes 1 et 2") +
  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
  ylab(paste("Axe 2 :",round(resultat_ACP$eig[2,2],0),"%")) +
  geom_circle( aes(x0 = 0, y0 = 0, r = 1), inherit.aes = F) +
  scale_x_continuous(limits = c(-1, 1)) +
  scale_y_continuous(limits = c(-1, 1)) +
  coord_fixed() +
  geom_segment(aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), arrow = arrow())

ggplot(data=dbind,aes(x=Dim.1,y=Dim.2, color = sensi_env, size = part_depenses_env))+
  ggtitle("Espace des pays dans l'ACP des variables")+
  geom_point()+
  geom_text_repel(aes(label = code),size=3)+
  geom_hline(yintercept=0,linetype="dashed")+
  geom_vline(xintercept = 0,linetype="dashed")+
  theme(plot.title=element_text(hjust=0.5),legend.position=c(0.1,.8),
        panel.background =element_rect(fill="white"),legend.title=element_blank())+
  labs(caption = "Plus un pays est en bleu clair, plus il est sensibilisé à l'environnement, \nplus le cercle est gros, plus ses dépenses pour l'environnement en points de PIB sont élevées.") +
  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
  ylab(paste("Axe 2 :",round(resultat_ACP$eig[2,2],0),"%"))

ggplot(dbact,aes(x=Dim.1,y= Dim.3,label=names))+
  geom_point()+
  theme(legend.title=element_blank(),
        panel.background =element_rect(fill="white")) +
  geom_text_repel(size=4,show.legend = FALSE)+
  geom_hline(yintercept=0,linetype="dashed",colour="grey")+
  geom_vline(xintercept = 0,linetype="dashed",colour="grey")+
  ggtitle("Espace des variables de l'ACP avec les axes 1 et 3") +
  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
  ylab(paste("Axe 3 :",round(resultat_ACP$eig[3,2],0),"%")) +
  geom_circle( aes(x0 = 0, y0 = 0, r = 1), inherit.aes = F) +
  scale_x_continuous(limits = c(-1, 1)) +
  scale_y_continuous(limits = c(-1, 1)) +
  coord_fixed() +
  geom_segment(aes(x = 0, y = 0, xend = Dim.1, yend = Dim.3), arrow = arrow())

ggplot(data=dbind,aes(x=Dim.1,y=Dim.3, color = sensi_env, size = part_depenses_env))+
  ggtitle("Espace des pays dans l'ACP des variables")+
  geom_point()+
  geom_text_repel(aes(label = code),size=3)+
  geom_hline(yintercept=0,linetype="dashed")+
  geom_vline(xintercept = 0,linetype="dashed")+
  theme(plot.title=element_text(hjust=0.5),legend.position=c(0.1,.8),
        panel.background =element_rect(fill="white"),legend.title=element_blank())+
  labs(caption = "Plus un pays est en bleu clair, plus il est sensibilisé à l'environnement, \nplus le cercle est gros, plus ses dépenses pour l'environnement en points de PIB sont élevées.") +
  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
  ylab(paste("Axe 3 :",round(resultat_ACP$eig[3,2],0),"%"))


```

## Annexe 5.


```{r}
graph3 <- ggplot(base_complete, aes (x = conn_env, y = perc_env)) + 
  geom_point(color = "darkgreen", size = 3 ) +
  geom_smooth (method = "lm", size = 1, lty = 1, se = 2, color = "black")

graph3 <- graph3 + labs(title = "Lien entre la connaissance des problèmes environnementaux et leur perception",
                        y = "Perception environnementale",
                        x = "Connaissance environnementale",
                        fill = NULL,
                        subtitle = "D'après l'Europen Values Survey")

print(graph3)

```

```{r}

graph4 <- ggplot(base_complete, aes (x = conn_env, y = soutien_pol_env)) + 
  geom_point(color = "darkgreen", size = 3 ) +
  geom_smooth (method = "lm", size = 1, lty = 1, se = 2, color = "black")

graph4 <- graph4 + labs(title = "Lien entre la connaissance des problèmes environnementaux et le soutien aux politiques environnementales",
                        y = "Soutien aux mesures de protection de l'environnement",
                        x = "Connaissance environnementale",
                        fill = NULL,
                        subtitle = "D'après l'Europen Values Survey")

print(graph4)

```

```{r}
graph5 <- ggplot(base_complete, aes (x = perc_env, y = soutien_pol_env)) + 
  geom_point(color = "darkgreen", size = 3 ) +
  geom_smooth (method = "lm", size = 1, lty = 1, se = 2, color = "black")

graph5 <- graph5 + labs(title = "Lien entre le soutien aux politiques environnementales et la perception des problèmes environnementaux",
                        y = "Soutien aux mesures de protection de l'environnement",
                        x = "Perception environnementale",
                        fill = NULL,
                        subtitle = "D'après l'Europen Values Survey")
print(graph5)

```


## Annexe 6

```{r}
correlation.matrix <- cor(base_complete[, 5:14]) 

correlation.matrix <- as.data.frame(correlation.matrix)

names(correlation.matrix)[names(correlation.matrix)=="REV_MED_EURO_2017"] <- "rev_median" 
names(correlation.matrix)[names(correlation.matrix)=="GINI_2017"] <- "ind_gini" 
names(correlation.matrix)[names(correlation.matrix)=="EDUC_SUP_2017"] <- "educ_sup"
names(correlation.matrix)[names(correlation.matrix)=="EPI.new"] <- "epi" 
names(correlation.matrix)[names(correlation.matrix)=="depenses_brutes_env"] <- "depenses_env" 

kbl(correlation.matrix[,1:5], caption = "Matrice des corrélations", digits = 3) %>%
  kable_classic()

kbl(correlation.matrix[,6:10], caption = "Matrice des corrélations (suite)", digits = 3) %>%
  kable_classic()

```

## Annexe 7

```{r}

ggcorrplot(cor(base_complete[,5:14]), title = "Représentation graphique \nde la matrice des corrélations", legend.title= "Corrélation", lab = T, lab_col = "black", lab_size = 2.5, colors = c("gray8", "white", "forestgreen"), tl.cex = 5)




```


## Annexe 8

```{r}
reg1    <- lm(data = base_complete, formula = part_depenses_env ~ sensi_env)
reg1bis <- lm(data=base_complete, formula = part_depenses_env ~ conn_env + perc_env + soutien_pol_env)
reg1ter <- lm(data = base_complete, formula = depenses_brutes_env ~ sensi_env)
reg1quater <- lm(data = base_complete, formula = depenses_brutes_env ~ conn_env + perc_env + soutien_pol_env)

```
 
```{r, results='asis'}
stargazer(reg1, reg1bis, reg1ter, reg1quater, title = "Modèles simples sans variables de contrôle.", header = F, column.labels =  c("reg1", "reg1bis", "reg1ter", "reg1quater"))

```

## Annexe 9

```{r}
reg2    <- lm(data = base_complete, formula = part_depenses_env ~ conn_env)
reg2bis <- lm(data=base_complete, formula = depenses_brutes_env ~ conn_env)

```
 
```{r, results='asis'}
stargazer(reg2, reg2bis, title = "Modèles sans variables de contrôle, avec une variable repérée comme significative.", header = F, column.labels = c("reg2", "reg2bis"))
```

## Annexe 10

```{r}
reg3   <- lm(data = base_complete, formula = part_depenses_env ~ sensi_env + EPI.new + REV_MED_EURO_2017 + EDUC_SUP_2017 + GINI_2017)
reg3bis <- lm(data=base_complete, formula = depenses_brutes_env ~ sensi_env + EPI.new + REV_MED_EURO_2017 + EDUC_SUP_2017 + GINI_2017)
reg4   <- lm(data = base_complete, formula = part_depenses_env ~ conn_env + EPI.new + REV_MED_EURO_2017 + EDUC_SUP_2017 + GINI_2017)
reg4bis <- lm(data=base_complete, formula = depenses_brutes_env ~ conn_env + EPI.new + REV_MED_EURO_2017 + EDUC_SUP_2017 + GINI_2017)

```
 
```{r, results='asis'}

stargazer(reg3,reg4,reg3bis,reg4bis, header = F, title = "Modèles avec variables de contrôle, pour sensi.env et conn.env.", column.labels =  c("reg3", "reg4", "reg3bis", "reg4bis"))

```

## Annexe 11

```{r}
reg5   <- lm(data = base_complete, formula = part_depenses_env ~ sensi_env + EPI.new + EDUC_SUP_2017 + GINI_2017)
reg5bis <- lm(data=base_complete, formula = depenses_brutes_env ~ sensi_env + EPI.new +  EDUC_SUP_2017)
reg6   <- lm(data = base_complete, formula = part_depenses_env ~ conn_env + EPI.new + EDUC_SUP_2017 + GINI_2017)
reg6bis <- lm(data=base_complete, formula = depenses_brutes_env ~ conn_env + EPI.new + EDUC_SUP_2017 + GINI_2017)

```
 
```{r, results='asis'}

stargazer(reg5,reg6,reg5bis,reg6bis, header = F, title = "Modèles avec variables de contrôle, sans educ.sup.", column.labels =  c("reg5", "reg6", "reg5bis", "reg6bis"))

```

## Annexe 12

```{r, results='asis'}

# mieux d'avoir un tableau comme pour les autres modèles en termes d'homogénéité.

reg7   <- lm(data = base_complete, formula = part_depenses_env ~ conn_env + soutien_pol_env + EPI.new + GINI_2017)

stargazer(reg7, header = F, title = "Modèles avec variables de contrôle, sans educ.sup ni rev.med.", column.labels =  c("reg7"))

```


## Annexe 13

```{r, results='asis'}

reg7   <- lm(data = base_complete, formula = part_depenses_env ~ conn_env + soutien_pol_env + EPI.new + GINI_2017)

stargazer(reg2,reg7, reg5bis, header = F, title = "Modèles retenus.", column.labels =  c("reg2", "reg7", "reg5bis"))

```

## Annexe 14

```{r}
plot(compare_performance(reg2,reg7, reg5bis), rank = TRUE)
```

## Annexe 15


```{r}

check_model(reg2, panel = T) 

```

## Annexe 16

```{r}

check_model(reg5bis, panel = T)
```

## Annexe 17

```{r}

check_model(reg7, panel = T)

```

<!-- ## Annexe 18 -->

<!-- ## Annexe 19 -->

<!-- ## Annexe 20 -->










