---
title: "code_stats"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

## Packages ----

library(dplyr)
library(tidyverse)
library(ggforce)
library(sf)
library(haven)
library(FactoMineR)
library(ggrepel)
library(readxl)
library(stargazer)
library(questionr)
#install.packages("remotes")
#remotes::install_github("easystats/easystats")
library("easystats")
#install.packages("ggraph")
library(ggraph)
library(dplyr)
library(see)

## Données -----

#setwd("C:/Users/quent/Desktop/ENS Paris-Saclay/1A/1S2/Econométrie/TDs/Bases de données/Documents")
setwd("~/Documents/ENS/econometrie/projet_r")


base_complete <- read.csv("base_complete.csv") %>%
 select(-X) 

base_exploration <- base_complete %>%
  select(-code2)
```

### Analyse univariée 

Nous procédons à une première analyse des variables présentes dans notre jeu de données. Pour ce faire, il s'agit de dresser un tableau des principaux indicateurs présents  :

```` {r, results = "asis" }

stargazer(base_exploration, type = 'html', title = "Principaux indicateurs des variables" )

graph1 <- ggplot(data = base_exploration, 
                 mapping = aes(y=Nom_pays, 
                               x = part_depenses_env,
                               fill = part_depenses_env)) +
  geom_col()

graph1 <- graph1 + labs(title = "Les dépenses nationales pour la protection de l'environnement des pays Européens",
         y = "Pays", 
         x = "Part des NEEP dans le PIB",
         fill = NULL,
         subtitle= "en points de PIB")

print(graph1)

graph2 <- ggplot(data = base_exploration, 
                 mapping = aes(y=Nom_pays, 
                               x = depenses_brutes_env,
                               fill = depenses_brutes_env)) +
  geom_col()

graph2 <- graph2 + labs(title = "Les dépenses nationales pour la protection de l'environnement des pays Européens",
         y = "Pays", 
         x = "NEEP brutes",
         fill = NULL,
         subtitle= "en million d'euros")

print(graph2)
  

````

### Analyse bivariée et analyse en composantes principales

```{r}
resultats_cor <- correlation(base_exploration)

resultats_cor <- summary(resultats_cor, redundant = TRUE)
print(resultats_cor)

```

```{r ACP-classification}

## Données ACP et Classification

resultat_ACP  <- PCA(base_complete[, 5:13])

dbact  <-as_tibble(resultat_ACP$var$coord) %>% 
  mutate(names=c(rownames(resultat_ACP$var$coord)))

dbind <- bind_cols(base_complete,as_tibble(resultat_ACP$ind$coord))

resultat_classif <- HCPC(resultat_ACP, nb.clust = 4, graph = FALSE)

dbind            <- dbind %>%
  ungroup() %>%
  mutate(groupe = resultat_classif$data.clust$clust)

## Graphiques ----

graph_acp1 <- barplot(resultat_ACP$eig[,2],main="Figure I - Part expliquée par chaque axe dans la variance totale",
         names.arg=1:nrow(resultat_ACP$eig),col= rainbow (15))

print(graph_acp1)
 
graph_acp2 <- ggplot(dbact,aes(x=Dim.1,y= Dim.2,label=names))+
  geom_point()+
  theme(legend.title=element_blank(),
        panel.background =element_rect(fill="white")) +
  geom_text(size=4,show.legend = FALSE)+
  geom_hline(yintercept=0,linetype="dashed",colour="grey")+
  geom_vline(xintercept = 0,linetype="dashed",colour="grey")+
  ggtitle("Espace des variables de l'ACP avec les axes 1 et 3") +
  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
  ylab(paste("Axe 2 :",round(resultat_ACP$eig[2,2],0),"%")) +
  geom_circle( aes(x0 = 0, y0 = 0, r = 1), inherit.aes = F) +  
  scale_x_continuous(limits = c(-1, 1)) +
  scale_y_continuous(limits = c(-1, 1)) +
  coord_fixed() +
  geom_segment(aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), arrow = arrow())

print(graph_acp2)

 
#ggplot(data=dbind,aes(x=Dim.1,y=Dim.2))+
 # ggtitle("Titre")+
#  geom_point()+
#  geom_text_repel(aes(label = c_abrv),size=3)+
#  geom_hline(yintercept=0,linetype="dashed")+
#  geom_vline(xintercept = 0,linetype="dashed")+
#  theme(plot.title=element_text(hjust=0.5),legend.position=c(.95,.2),
#       panel.background =element_rect(fill="white"),legend.title=element_blank())+
#  xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
#  ylab(paste("Axe 2 :",round(resultat_ACP$eig[2,2],0),"%"))

# ggplot(data=dbind,aes(x=Dim.1,y=Dim.2))+
#   ggtitle("Titre")+
#   geom_point(aes(color=groupe))+
#   geom_text_repel(aes(color=groupe,label=c_abrv),
#                   size=3, max.overlaps = 20, max.iter = 1000)+
#   geom_hline(yintercept=0,linetype="dashed")+
#   geom_vline(xintercept = 0,linetype="dashed")+
#   theme(plot.title=element_text(hjust=0.5),
#         panel.background =element_rect(fill="white"))+
#   xlab(paste("Axe 1 :",round(resultat_ACP$eig[1,2],0),"%"))+
#   ylab(paste("Axe 2 :",round(resultat_ACP$eig[2,2],0),"%"))+ 
#   guides(color = F)
# 
# ggplot(data = carte_europe) +
#   geom_sf(aes(fill = groupe)) + 
#   guides(fill = F) +
#   ggtitle("Figure VI - Carte des pays classifiés selon les opinions agrégées sur l'environnement") +
#   coord_sf(datum = NA)





```