---
title: "Partie qui pose problème"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

## Packages ----

library(tidyverse)
library(ggforce)
library(sf)
library(haven)
library(FactoMineR)
library(ggrepel)
library(stargazer)
library(questionr)
#install.packages("remotes")
#remotes::install_github("easystats/easystats")
#install.packages("qqplotr")
library(qqplotr)
library(easystats)
#install.packages("ggraph")
library(ggraph)
library(dplyr)
library(see)

# install.packages("corrplot")                      # Install corrplot package
# library("corrplot")  

## Données -----

setwd("C:/Users/quent/Desktop/ENS Paris-Saclay/1A/1S2/Econométrie/TDs/Bases de données/Documents/projet-econometrie")
# setwd("~/Documents/ENS/econometrie/projet_r")

base_complete <- read_csv("base_complete.csv") %>%
   mutate(code2 = as.character(code2))

```

## Annexe 5

```{r}
#

# corrplot(cor(base_complete[,5:14]), method = "circle")    # Apply corrplot function
# 
# 
# 
# resultats_cor <- correlation(base_complete)
# 
# resultats_cor <- summary(resultats_cor, redundant = TRUE)
# print(resultats_cor)
# 
# graph_cor <- resultats_cor %>%
#   summary(redundant = TRUE)
# 
#   plot(graph_cor, show_values = TRUE, show_p = TRUE, show_legend = TRUE)

#print(graph_cor)

graph_cor2 <- base_complete %>%
 correlation(partial = TRUE) %>%
 plot(main = "Modèle graphique gaussien des corrélations partiales entre les variables")

 print(graph_cor2)

```